### PR TITLE
Docker-Compose Version 2

### PR DESCRIPTION
**Pull request by whatever4711**
Updated Docker-Compose to Version 2, which simplifies network setup.

### CODE REVIEW

**Comment by firecyberice** [comment]
I think we should remove the binaries and Dockerfile and fix hypriot/rpi-consul-template instead.

**Comment by firecyberice** [comment]
After digging deeper into the code I discovered that you only need to update your host docker version to min 1.10. We should maybe add docker version 1.10 as requirement.

**Comment by MathiasRenner** [comment]
Also see https://github.com/hypriot/rpi-consul-template/issues/2#issuecomment-183469650

**Comment by MathiasRenner** [comment]
After some discussions with @firecyberice, we decided to merge the PR **with** binaries and delete them after merge.

**Pull request merged**
